---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom
  namespace: default
  labels:
    app: prom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom
  template:
    metadata:
      annotations:
        prometheus.io/port: "2112"
        prometheus.io/scrape: "true"
      labels:
        app: prom
    spec:
      containers:
        - name: prom
          image: prom:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2112
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prom
    release: prometheus
  name: prom
  namespace: default
spec:
  ports:
    - name: "2112"
      port: 2112
      protocol: TCP
      targetPort: 2112
  selector:
    app: prom
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prom
  namespace: default
  labels:
    release: prometheus
spec:
  endpoints:
    - interval: 5s
      path: /metrics
      port: "2112"
      scrapeTimeout: 5s
  selector:
    matchLabels:
      app: prom
      release: prometheus
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: PrometheusRule
# metadata:
#   name: prom-slo-rules
#   namespace: default
#   labels:
#     release: prometheus
# spec:
#   groups:
#     - name: prom_slo_rules
#       interval: 1m
#       rules:
#         - alert: AvailabilitySLOViolation
#           expr: sum(rate(http_requests_total{service="prom",status=~"2.."}[5m]))
#             / sum(rate(http_requests_total{service="prom"}[5m])) < 0.999
#           for: 5m
#           labels:
#             severity: critical
#           annotations:
#             summary: "Availability SLO violated for prom service"
#             description: "Availability dropped below 99.9% for more than 5 minutes."

#         - alert: ErrorRateSLOViolation
#           expr: sum(rate(http_requests_total{service="prom",status=~"5.."}[5m]))
#             / sum(rate(http_requests_total{service="prom"}[5m])) > 0.001
#           for: 5m
#           labels:
#             severity: warning
#           annotations:
#             summary: "Error rate SLO violated for prom service"
#             description: "Error rate exceeded 0.1% for more than 5 minutes."

#         - alert: LatencyP95SLOViolation
#           expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{service="prom"}[5m])) by (le)) > 0.5
#           for: 5m
#           labels:
#             severity: warning
#           annotations:
#             summary: "Latency p95 SLO violated for prom service"
#             description: "95th percentile latency exceeded 500ms for more than 5 minutes."

#         - alert: ErrorBudgetViolation
#           expr: 1 - (sum(rate(http_requests_total{service="prom",status=~"5.."}[5m])) / sum(rate(http_requests_total{service="prom"}[5m]))) / 0.001 < 0
#           for: 5m
#           labels:
#             severity: critical
#           annotations:
#             summary: "Error budget exhausted for prom service"
#             description: "The error budget for prom service has been fully consumed."
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: AlertmanagerConfig
# metadata:
#   name: prom-alert-config
#   namespace: monitoring
# spec:
#   route:
#     receiver: slack-receiver
#     groupWait: 30s
#     groupInterval: 5m
#     repeatInterval: 1h
#   receivers:
#     - name: slack-receiver
#       slackConfigs:
#         - apiURL: https://hooks.slack.com/services/T000/B000/XXXX
#           channel: "#alerts"

