---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom
  labels:
    app: prom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom
  template:
    metadata:
      annotations:
        prometheus.io/port: "2112"
        prometheus.io/scrape: "true"
      labels:
        app: prom
    spec:
      containers:
        - name: prom
          image: prom:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2112
---
apiVersion: v1
kind: Service
metadata:
  name: prom
  labels:
    app: prom
spec:
  ports:
    - port: 2112
      targetPort: 2112
      protocol: TCP
  selector:
    app: prom
